---
title: "create graph to visalize order of execution for scripts"
output: html_document
---

```{r setup, include=FALSE}
library(DiagrammeR)
library(rsvg)
library(DiagrammeRsvg)
library(here)
here()
```

# create and plot graph

```{r graph}
grViz("
digraph boxes_and_circles {

  # a 'graph' statement
  graph [overlap = true, fontsize = 10]

  # several 'node' statements
  node [shape = box,
        fontname = Helvetica]
  A; B; C; E


  
    # node definitions with substituted label text
  node [fontname = Helvetica]
  A [label = 'prep_individuals.Rmd']
  B [label = 'prep_households.Rmd']
  C [label = 'prep_map_2016.Rmd']
  D [label = 'Predictors.Rmd']

  E [label = 'LanguagePairs.Rmd']
  F [label = 'Geo_Percentages.Rmd']
  G [label = 'Plot_Map_2016.Rmd']


  # several 'edge' statements
  A->E A->F F->G C->G
  B->D 
}
") %>%
export_svg %>% charToRaw %>% rsvg_png(here("03_output/BilCan_Script_Overview.png"),  width = 2000, height = 700)
```

